name: docs

# Trigger the action on push to main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  actions: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  EXILED_REFERENCES_URL: https://Exiled-Official.github.io/SL-References/Dev.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/EXILED/References

defaults:
  run:
    working-directory: ./EXILED
  
jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Framework
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --includeRecommended --includeOptional"
        choco install netfx-4.8-devpack
        
    - name: Setup Nuget
      uses: iRebbok/setup-nuget@master
        
    - name: Get references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri $env:EXILED_REFERENCES_URL -OutFile $env:GITHUB_WORKSPACE/EXILED/References.zip
        Expand-Archive -Path $env:GITHUB_WORKSPACE/EXILED/References.zip -DestinationPath $env:EXILED_REFERENCES_PATH

    - name: Install DocFX
      run: dotnet tool update -g docfx

    - name: Build Documentation
      run: docfx docfx.json

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: '_site'
        target_branch: gh-pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
